# Generated by Django 4.2.4 on 2023-08-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="fifa_code",
            field=models.CharField(default="", max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name="team",
            name="first_cup",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="team",
            name="titles",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="top_scorer",
            field=models.CharField(default="", max_length=50),
        ),
    ]
